# SPDX-FileCopyrightText: 2021 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and check
    steps:
      - uses: actions/checkout@v2
        with:
          path: webidl
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1
        with:
          args: --root webidl lint
      - name: Build RPM
        uses: reznikmm/fedora-ada-action@v3
        with:
          spec: webidl/packages/webidl.spec
